name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: npm test
